### ISSUE TITLE
首先感谢分享代码，我在使用时遇到了一些问题，请帮忙解答一下

### ISSUE THREAD

**Issue by papersuper** [wenwenyu/TCM#13]

**Comment by papersuper** [comment]
当执行python ./tools/det_test_imgs.py   --score-thr  0.5 --out-dir ./results_out/  --device cuda:0  ./tools  image_16.jpg  ./configs/textdet/dbnet/clip_db_r50_fpnc_prompt_gen_vis_1200e_ft_gen_ic15_adam_taiji.py  ./pretrained/best_0_icdar2015_test_hmean-iou.hmean_epoch_640.pth 时报错

Traceback (most recent call last):
  File "D:\app\anaconda\envs\open-mmlab\lib\site-packages\mmcv\utils\misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "D:\app\anaconda\envs\open-mmlab\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ocrclip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/det_test_imgs.py", line 114, in <module>
    main()
  File "./tools/det_test_imgs.py", line 76, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "D:\app\anaconda\envs\open-mmlab\lib\site-packages\mmocr\apis\inference.py", line 34, in init_detector
    config = mmcv.Config.fromfile(config)
  File "D:\app\anaconda\envs\open-mmlab\lib\site-packages\mmcv\utils\config.py", line 334, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "D:\app\anaconda\envs\open-mmlab\lib\site-packages\mmcv\utils\misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

**Comment by papersuper** [comment]
i have the same problem

**Comment by lishiyi1111** [comment]
请问解决了吗
